### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by jdecool** [icomefromthenet/ReverseRegex#11]
[PHP 8.0 was released](https://www.php.net/archive/2020.php#2020-11-26-3) 3 days ago.

I would be great to add the compatibility.

**Comment by enso-san** [comment]
I forked the library, made it compatible for PHP 8 and fixed some tests:
https://github.com/enso-media/ReverseRegex
Released it also as v0.2 on Packagist:
`composer require enso-media/reverse-regex`
You can use it as a drop-in replacement for the original library.
All credits stays of course for @icomefromthenet for his great work with this lib.

**Comment by jdecool** [comment]
I close this PR, the library is abandoned. 

#12
