### ISSUE TITLE
Does this library maintained anymore ?

### ISSUE THREAD

**Issue by jdecool** [icomefromthenet/ReverseRegex#12]
It seems to have no more activity since few month.

Last commits maded in June and 2 years ago before that. 
The Travis build is broken, and there is some issue with dependencies (see #8 #9 and #11).

So does this library is maintained anymore ?

Do you need help ?

**Comment by enso-san** [comment]
I forked the library, made it compatible for PHP 8 and fixed some tests:
https://github.com/enso-media/ReverseRegex
Released it also as v0.2 on Packagist:
`composer require enso-media/reverse-regex`
You can use it as a drop-in replacement for the original library.
All credits stays of course for @icomefromthenet for his great work with this lib.

**Comment by pointybeard** [comment]
It's obvious at this point this library has been abandoned. I've tried to fix/refactor all the outstanding issues. You can see them in my fork <https://github.com/pointybeard-forks/ReverseRegex>.

**Comment by jdecool** [comment]
I close this issue.

This library is definitively abandoned !
I've replace it usage by some custom code.
